### PR TITLE
Update install.rst

### PR DESCRIPTION
**Pull request by s-broda**
Windows installation notes

### CODE REVIEW

**Comment by lkuper** [comment]
@s-broda Can you sign the [contributor agreement](https://www.clahub.com/agreements/IntelLabs/ParallelAccelerator.jl)?  Don't worry about the AppVeyor check.

**Comment by lkuper** [comment]
@IntelLabs/team-hps Do y'all have any problems with integrating this patch?  I think we should do it, although with a note that Windows support is experimental.

**Comment by lkuper** [comment]
On second thought, I'm no longer so sure that we want to encourage people to go the mingw route.  Will it play nicely with people's Julia binaries that were built natively for Windows?  See discussion in #75.

**Comment by tkelman** [comment]
mingw is native windows.

**Comment by s-broda** [comment]
Closing; see discussion in #75.

**Pull request closed without merging**
